### ISSUE TITLE
no error handling dataHandler

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/morsecode#3]
https://github.com/WebAhead7/morsecode/blob/master/handlers/dataHandler.js#L15

in case an error occurs this line of code is throwing an error which means it will crash you server, it would be better if we handled this error and sent an appropriate response

**Comment by Karyum** [comment]
also here
https://github.com/WebAhead7/morsecode/blob/master/public/index.js#L20-L22

**Comment by ghost** [comment]
done
